import { defineField, defineType } from "sanity";

export default defineType({
  name: "order",
  title: "Order",
  type: "document",
  fields: [
    defineField({
      name: "orderNumber",
      title: "Order Number",
      type: "string",
      readOnly: true,
      initialValue: () => `ORD-${Date.now()}`,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "productName",
      title: "Product Name",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "customerName",
      title: "Customer Name",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "customerPhone",
      title: "Customer Phone",
      type: "string",
      validation: (Rule) =>
        Rule.required()
          .regex(/^[0-9]{11}$/, {
            name: "phone",
            invert: false,
          })
          .error("Phone number must be 11 digits"),
    }),
    defineField({
      name: "customerAddress",
      title: "Customer Address",
      type: "text",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "quantity",
      title: "Quantity",
      type: "number",
      validation: (Rule) => Rule.required().positive().integer(),
      initialValue: 1,
    }),
    defineField({
      name: "unitPrice",
      title: "Unit Price",
      type: "number",
      validation: (Rule) => Rule.required().positive(),
      description: "Price per unit at the time of order",
    }),
    defineField({
      name: "totalPrice",
      title: "Total Price",
      type: "number",
      validation: (Rule) => Rule.required().positive(),
      description: "Total order amount (unitPrice × quantity)",
    }),
    defineField({
      name: "currency",
      title: "Currency",
      type: "string",
      initialValue: "৳",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "paymentMethod",
      title: "Payment Method",
      type: "string",
      options: {
        list: [
          { title: "Cash on Delivery (COD)", value: "cod" },
          { title: "Online Payment", value: "online" },
          { title: "Bank Transfer", value: "bank" },
        ],
      },
      initialValue: "cod",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "orderStatus",
      title: "Order Status",
      type: "string",
      options: {
        list: [
          { title: "Pending Review", value: "pending" },
          { title: "Approved", value: "approved" },
          { title: "Sent to Courier", value: "sent_to_courier" },
          { title: "Delivered", value: "delivered" },
          { title: "Cancelled", value: "cancelled" },
        ],
      },
      initialValue: "pending_review", // Changed from "pending"
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "ipAddress",
      title: "IP Address",
      type: "string",
    }),

    // Courier Integration Fields (NEW)
    defineField({
      name: "trackingCode",
      title: "Tracking Code",
      type: "string",
      readOnly: true, // Auto-filled when sent to courier
      description: "Auto-generated by courier service",
    }),
    defineField({
      name: "consignmentId",
      title: "Consignment ID",
      type: "number",
      readOnly: true,
      description: "Auto-generated by Steadfast Courier",
    }),
    defineField({
      name: "sentToCourierAt",
      title: "Sent to Courier At",
      type: "datetime",
      readOnly: true,
    }),

    defineField({
      name: "orderedAt",
      title: "Ordered At",
      type: "datetime",
      validation: (Rule) => Rule.required(),
      initialValue: () => new Date().toISOString(),
    }),
  ],
  preview: {
    select: {
      orderNumber: "orderNumber",
      customerName: "customerName",
      productName: "productName",
      orderStatus: "orderStatus",
      totalPrice: "totalPrice",
      currency: "currency",
      trackingCode: "trackingCode", // Added tracking code
    },
    prepare({
      orderNumber,
      customerName,
      productName,
      orderStatus,
      totalPrice,
      currency,
      trackingCode,
    }) {
      return {
        title: `${orderNumber || "Order"} - ${customerName || "Unknown"}`,
        subtitle: `${productName || "Product"} | ${currency || "৳"}${totalPrice || 0} | ${orderStatus || "pending"} ${trackingCode ? `| Track: ${trackingCode}` : ""}`,
      };
    },
  },
  orderings: [
    {
      title: "Order Date (Newest)",
      name: "orderedAtDesc",
      by: [{ field: "orderedAt", direction: "desc" }],
    },
    {
      title: "Order Date (Oldest)",
      name: "orderedAtAsc",
      by: [{ field: "orderedAt", direction: "asc" }],
    },
    {
      title: "Order Number",
      name: "orderNumberAsc",
      by: [{ field: "orderNumber", direction: "asc" }],
    },
  ],
});
